### ISSUE TITLE
Cerebro Milestones Tracker

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/data-ops#41]
# Cerebro Milestones Tracker

## Why Cerebro

Gitcoin's brand promise is to connect coders/contributors/hackers to funders and sponsors who are looking for skilled workers. 

While we do this already, Cerebro is the foundational component that allows us to utilize the breadth of data on our contributors to match them using a variety of data points, either to relevant bounties or specific characteristics that funders are looking for. Essentially, it is an extensible tool with inputs and relevant outputs that can be used on both sides of the marketplace.

1. For example, Cerebro would aid a contributor with a Gitcoin profile, skills, and accomplishments and expose him/her to bounties that fit their experience, and/or funders and sponsors who are working on relevant projects.

2. With the input of desired search characteristics ("I want an 3-year experienced frontend developer who is good at solidity, has reputation on Gitcoin and Github to help me with my project dealing with ethereum wallets"), funders and sponsors can get a ranked list of potential contributors and hackers to reach out to, decreasing the amount of time and the probability of a bad match.

3. Cerebro also has its uses outside the Gitcoin network. Eventually it would be able to digest information outside the Gitcoin social network and provide introductions to potential hackers that have not yet discovered the Gitcoin platform.

## Existing Work

Currently, a barebones v1 of Cerebro has been put up here that consumes available Gitcoin data: https://github.com/gitcoinco/web/pull/5464

## Milestone 1

The first milestone will most likely involve the POC-PR that Kevin built (above) and running with that to see if it can generate positive match results for actual Gitcoin members. Our previous matching between a contributor and a bounty is purely done by tag skill matching.

1. So, given a Gitcoin member's profile information, can we generate like-minded contributors they would be interested in, and bounties that are a good match for them using this ML-algorithm?

2. Given these new matches, what do actual users think about them?

3. What are the measures and proxy-measures of success between how we did matching before and this new algorithm?

The output of this milestone would look like:

- [ ] productionize the algorithm
- [ ] use the algorithm to generate matches in the `new_bounty` emails that go out
- [ ] measure previous CTRs and new CTRs using the matching algorithm
- [ ] measure retention curve of email open rates
- [ ] this will give an idea whether or not the algorithm has the desired impact, and/or if we need more data to make better predictions

## Milestone 2

The second milestone will involve data beyond just the Gitcoin atmosphere, and will involve the identification and cataloguing of existing known developers. For milestone II, this means focusing entirely on Github profiles using their public API. This will entail being able to query a list of active Gitcoin users and consuming additional data that doesn't currently exist within Gitcoin.

Kames is creating a UI similar to https://www.entelo.com/ which he can demo for you if you ask. 

A successful milestone II means correlating existing Gitcoin data with collected Github data and/or additional existing social networks (twitter, telegram, . The usefulness of this action is currently unknown, and necessitates a deeper exploratory, manual analysis. This analysis may be done in parallel with milestone I, but it may not confirm the ultimate impact of the algorithm itself. 

- [ ] github api & incorporating this additional data into the algorithm
- [ ] what technologies are used by gitcoin contributors
- [ ] what repositories are followed
- [ ] tag and categories followed
- [ ] commit behavior
- [ ] organizations

the ultimate question in milestone II:
- [ ] if milestone I does indeed yield better matches, does including github data yield better matches?

if yes, then we can take this as far as scraping additional social media sources to increase our data breadth - correlating telegram interactions with Gitcoin hackathons, and even twitter interactions with Gitcoin Grants.

## Milestone 3

Once we had a better understanding of what type of data is relevant and what is usable, there can be a build out and optimization of an Application Dashboard to allow Gitcoin team members to better interact with that collected data, so marketing campaigns, user search, or even reaching out 1-on-1 could be done more effectively.

At this stage, this becomes more of a surfaced-tool that funders (mainly) but also contributors can interact with and get outputs from a customized source of inputs. 

If you're thinking about a search functionality on gitcoin.co, as it currently stands, gitcoin.co/users is a user and organization search, centered around basic inputs like personas, leaderboard rank, and skills, but these are mostly non-dynamic data points that allows one contributor to search for another contributor. By this stage, we will have proven that we do have enhanced matching capability, and will begin turning this from a backend, non-surfaced power to a more user-centric model where people can choose their inputs and outputs for what they're custom-looking for. 

This also necessitates a certain size of network to be efficient as well. 

## Milestone 4

Further milestones will be based off trajectories of previous milestones.

**Comment by owocki** [comment]
this looks really thought out to me :) kudos

productionizing what i did at ethwaterloo is probably a good starting point.  if we can just run the collaborative filtering in prod and train our 'recommended users' module that way it could result in a lot of new tribes followers

**Comment by owocki** [comment]
@frankchen07 happy to spend 1/2 hou8r on this sometime soon if u want

**Comment by think-in-universe** [comment]
this issue seems to be something I'm quite interested to help with, and did some research before (for example Milestone 2). happy to join the efforts.  @frankchen07

**Comment by frankchen07** [comment]
@think-in-universe - approved you, messaged you on gitcoin chat too, let's chat there!
