### ISSUE TITLE
Gitcoin Matching (Cerebro) - Use Case #1

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/data-ops#42]
## Why

From the Milestones tracker: https://github.com/gitcoinco/data-ops/issues/41

Gitcoin's brand promise is to connect coders/contributors/hackers to funders and sponsors who are looking for skilled workers. 

While we do this already, Cerebro is the foundational component that allows us to utilize the breadth of data on our contributors to match them using a variety of data points, either to relevant bounties or specific characteristics that funders are looking for. Essentially, it is an extensible tool with inputs and relevant outputs that can be used on both sides of the marketplace.

1. For example, Cerebro would aid a contributor with a Gitcoin profile, skills, and accomplishments and expose him/her to bounties that fit their experience, and/or funders and sponsors who are working on relevant projects.

## Existing Work

Currently, a barebones v1 of Cerebro has been put up here that consumes available Gitcoin data: https://github.com/gitcoinco/web/pull/5464

## Milestone 1

The first milestone will most likely involve the POC-PR that Kevin built (above) and running with that to see if it can generate positive match results for actual Gitcoin members. Our previous matching between a contributor and a bounty is purely done by tag skill matching (in the daily email).

1. So, given a Gitcoin member's profile information, can we 1. generate like-minded contributors they would be interested in, and 2. bounties that are a good match for them using this ML-algorithm?

2. Build the output of these matches into the daily email (currently IP https://github.com/gitcoinco/web/issues/6011)

3. Given these new matches, what do actual users think about them?

4. What are the measures and proxy-measures of success between how we did matching before and this new algorithm?

The output of this milestone would look like:

- [ ] productionize the algorithm
- [ ] use the algorithm to generate matches in the `new_bounty` emails that go out
- [ ] measure previous CTRs and new CTRs using the matching algorithm
- [ ] measure retention curve of email open rates
- [ ] this will give an idea whether or not the algorithm has the desired impact, and/or if we need more data to make better predictions

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.5 ETH (113.5 USD @ $227.0/ETH)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $82,274.31 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 266 years, 8 months from now.
Please review their action plans below:


**1) [abhayjindal51](https://gitcoin.co/abhayjindal51) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?mutate_worker_action=approve&worker=abhayjindal51) | [reject worker](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?mutate_worker_action=reject&worker=abhayjindal51))_.**

I would like to work on this project. The instructions are very clear. I would start with going through the codebase and then proceed as per the plan given.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079).

**Comment by frankchen07** [comment]
@abhayjindal51 - thanks for jumping in on this bounty.

If you can, please provide a brief timeline of your work, and when you might be able to get an integration WIP PR in so we can track your progress!

Looking forward to seeing your work! Let me know if you have any additional questions.

Feel free to pop in at gitcoin.co/chat and join our chat server so we can have a place for 1:1 conversations!

**Comment by gitcoinbot** [comment]
@abhayjindal51 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=100)

**Comment by gitcoinbot** [comment]
@abhayjindal51 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=100)

**Comment by abhayjindal51** [comment]
Yes I am working on this issue

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 266 years, 6 months from now.
Please review their action plans below:


**1) [srisankethu](https://gitcoin.co/srisankethu) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?mutate_worker_action=approve&worker=srisankethu) | [reject worker](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?mutate_worker_action=reject&worker=srisankethu))_.**

Experienced in data analysis using Python
**2) [jotafan](https://gitcoin.co/jotafan) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?mutate_worker_action=approve&worker=jotafan) | [reject worker](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?mutate_worker_action=reject&worker=jotafan))_.**

Dont really know where to start. way off the project, but I'm a data scientist, used to work with python. Really want to help out
**3) [wubswurld](https://gitcoin.co/wubswurld) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?mutate_worker_action=approve&worker=wubswurld) | [reject worker](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?mutate_worker_action=reject&worker=wubswurld))_.**

I would like to work on this bounty
**4) [think-in-universe](https://gitcoin.co/think-in-universe) has been approved to start work.**

Thanks for the invitation Frank. The issue seems fun to me, and I'm happy to contribute.

There're a few details I need to take a look and we may discuss on GitCoin chat or Discord. 

In the meanwhile, when I'm fixing the issue of 3box integration, it would be interesting to view how we can best utilize the data to achieve more values to all.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079).

**Comment by gitcoinbot** [comment]
@think-in-universe Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=100)

**Comment by frankchen07** [comment]
snoozed the bot for 10 days. Hit me up for any questions, looking forward to seeing how you progress! :)

**Comment by think-in-universe** [comment]
@frankchen07 thanks Frank~ Quite busy in the past few days. I'll take a look at the 3Box issue for Kevin and also this one today.

**Comment by gitcoinbot** [comment]
@think-in-universe Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/data-ops/42/4079?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__The funding of 0.5 ETH  (98.54 USD @ $197.09/ETH) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $85,758.29 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
